// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBANNaakvIAsXRLErUxaBhe6_KzAW_39X4',
    appId: '1:229477297961:web:520fafde45d27198c89138',
    messagingSenderId: '229477297961',
    projectId: 'unimarket-app-da613',
    authDomain: 'unimarket-app-da613.firebaseapp.com',
    storageBucket: 'unimarket-app-da613.appspot.com',
    measurementId: 'G-77VLLH9QLT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKiHT3YEpegBoj11NEH6kuxe9VJtxfFLU',
    appId: '1:229477297961:android:96d49e9a0bdd87cac89138',
    messagingSenderId: '229477297961',
    projectId: 'unimarket-app-da613',
    storageBucket: 'unimarket-app-da613.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxlesat_ogQMMpll6IFcqs253loadj2IQ',
    appId: '1:229477297961:ios:fa829c084979575ec89138',
    messagingSenderId: '229477297961',
    projectId: 'unimarket-app-da613',
    storageBucket: 'unimarket-app-da613.appspot.com',
    iosBundleId: 'com.example.unimarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxlesat_ogQMMpll6IFcqs253loadj2IQ',
    appId: '1:229477297961:ios:d7bda61b54e75838c89138',
    messagingSenderId: '229477297961',
    projectId: 'unimarket-app-da613',
    storageBucket: 'unimarket-app-da613.appspot.com',
    iosBundleId: 'com.example.unimarket.RunnerTests',
  );
}
